### ISSUE TITLE
When first create egressgateway CR，the status of IPV4/IPV6 TOTAL or IPV4/IPV6 FREE is emtpy

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#1245]
The egressgateway  yaml
```
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  name: egw-test
spec:
  ippools:
    ipv4:
    - 172.18.1.2-172.18.4.33
    ipv6:
    - fd18::2-fd18::321
  nodeSelector:
    selector:
      matchLabels:
        egress: "yes"
```

After create it
```bash
 kubectl get egw egw-test -oyaml

apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"egressgateway.spidernet.io/v1beta1","kind":"EgressGateway","metadata":{"annotations":{},"name":"egw-test"},"spec":{"ippools":{"ipv4":["172.18.1.2-172.18.4.33"],"ipv6":["fd18::2-fd18::321"]},"nodeSelector":{"selector":{"matchLabels":{"egress":"yes"}}}}}
  creationTimestamp: "2024-03-06T06:29:49Z"
  finalizers:
  - egressgateway.spidernet.io/egressgateway
  generation: 1
  name: egw-test
  resourceVersion: "51377"
  uid: da828623-23f6-4ea3-afee-200cda100197
spec:
  ippools:
    ipv4:
    - 172.18.1.2-172.18.4.33
    ipv4DefaultEIP: 172.18.3.138
    ipv6:
    - fd18::2-fd18::321
    ipv6DefaultEIP: fd18::122
  nodeSelector:
    selector:
      matchLabels:
        egress: "yes"

```

The status is not update

**Comment by jewelswain** [comment]
I am testing his Egressgateway and i would like Deploy the Egressgateway with IPV6 only , could u please help me out 
global:
  ## @param global.imageRegistryOverride The global image registry override
  imageRegistryOverride: ""
  ## @param global.imageTagOverride The global image tag override
  imageTagOverride: ""
  ## @param global.name instance name
  ## default egressgateway
  name: "egressgateway"
  ## @param global.clusterDnsDomain cluster dns domain
  clusterDnsDomain: "cluster.local"
  ## @param global.commonAnnotations Annotations to add to all deployed objects
  commonAnnotations: {}
  ## @param global.commonLabels Labels to add to all deployed objects
  commonLabels: {}
  #  label1: v1
  #  label2: v2

  ## @param global.configName the configmap name
  configName: "egressgateway"
## @section Feature parameters
feature:
  ## @param feature.enableIPv4 Enable IPv4
  enableIPv4: false
  ## @param feature.enableIPv6 Enable IPv6
  enableIPv6: true
  ## @param feature.datapathMode iptables mode, [`iptables`, `ebpf`]
  datapathMode: "iptables"
  ## @param feature.tunnelIpv4Subnet Tunnel IPv4 subnet
  #tunnelIpv4Subnet: "x.x.x.x/20"
  ## @param feature.tunnelIpv6Subnet Tunnel IPv6 subnet
  tunnelIpv6Subnet: "x:x:x:x::x/120"
  ## @param feature.tunnelDetectMethod Tunnel base on which interface [`defaultRouteInterface`, `interface=eth0`]
  tunnelDetectMethod: "defaultRouteInterface"
  ## @param feature.enableGatewayReplyRoute  the gateway node reply route is enabled, which should be enabled for spiderpool
  enableGatewayReplyRoute: false
  ## @param feature.gatewayReplyRouteTable  host Reply routing table number on gateway node
  gatewayReplyRouteTable: 600
  ## @param feature.gatewayReplyRouteMark  host iptables mark for reply packet on gateway node
  gatewayReplyRouteMark: 39
  iptables:
    ## @param feature.iptables.backendMode Iptables mode can be specified as `nft` or `legacy`, with `auto` meaning automatic detection. The default value is `auto`.
    backendMode: "auto"
"values.yaml" 436L, 22536C


Getting below 
 kubectl get EgressPolicy test -n test -o yaml
   egressIP:
    allocatorPolicy: default
    useNodeIP: false
