### ISSUE TITLE
nettools  opt

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#261]
(1) 优化1  , server
<img width="850" alt="企业微信截图_7d9681cc-4e39-4529-93fb-8707734b6a25" src="https://user-images.githubusercontent.com/45163302/229003860-56db42c1-f76e-47af-86a5-2d7d18a89579.png">

（2） 优化2  , client
client ，可以是 支持  压测 用法，输入 命令行参数 “目标地址（v4 v6）” “tps” “压测时间” “每个请求的超时时间定义” 等等，
最终输出 成功率 等等输出
后续 E2E 压测等，皆可 复用该 程序

**Comment by lou-lan** [comment]
nettools 已经经过重构
