### ISSUE TITLE
the status.physicalInterface of the egressnode cr have not been upgrade after i changed the node interface name

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#274]
**Describe the version**
egressgateway v0.1.0

**Describe the bug**
the status.physicalInterface of the egressnode cr have not been upgrade after i changed the node interface name

**Hwo To Reproduce**
Steps to reproduce the issue:
1. change the interface name of one one of your cluster
2. check the status.physicalInterface of the egressnode cr on the node

**Expected behavior**
we expect that the status.physicalInterface of the egressnode cr would be upgraded same with the node interface name

**Screenshots and log**
![image](https://user-images.githubusercontent.com/86399306/230849067-a1f6f6ca-c9c7-4d76-8971-0ef887f56682.png)
![image](https://user-images.githubusercontent.com/86399306/230851528-1844678d-a4b8-4c77-9fd2-85d6f439e867.png)

**Comment by lou-lan** [comment]
Resolved after feature eip was merged

**Comment by lou-lan** [comment]
old version
