### ISSUE TITLE
after changing the mac address of egress.vxlan on the node, the mac address did not restore its original value based on the egressnode cr status.tunnelMac

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#275]
**Describe the version**
egressgateway v0.1.0

**Describe the bug**
after changing the mac address of egress.vxlan on the node, the mac address did not restore its original value based on the egressnode cr status.tunnelMac

**Hwo To Reproduce**
Steps to reproduce the issue:
1. check egressnode cr egressgateway-worker status.tunnelMac
![image](https://user-images.githubusercontent.com/86399306/230853835-7ff14e24-d9bb-4ee6-afe8-419bf00ef1da.png)
2. change the egress.vxlan mac address
![image](https://user-images.githubusercontent.com/86399306/230854180-372ed475-abc7-4fe8-8e9a-6c73ea6e216a.png)
3. the mac address did not restore its original value based on the egressnode cr status.tunnelMac

**Expected behavior**
the mac address should restore its original value based on the egressnode cr status.tunnelMac

**Comment by bzsuni** [comment]
design implementation has changed?

**Comment by lou-lan** [comment]
In proposel, if vxlan device mac not euqal `egressnode.status.mac`, it will be update from crd.

**Comment by lou-lan** [comment]
old version
