### ISSUE TITLE
egressClusterInfo 'default' field egressIgnoreCIDR.clusterIP.ipv4 error when the cluster is ipv6

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#335]
egressClusterInfo 'default' field egressIgnoreCIDR.clusterIP.ipv4 error when the cluster is ipv6

![image](https://github.com/spidernet-io/egressgateway/assets/86399306/5e7c5737-7f9f-410e-98ab-a13f94785fff)

**Comment by ty-dc** [comment]
Add some comments in due course, to sync up the progress of the issue? :)
