### ISSUE TITLE
Controller exits abnormally

### ISSUE THREAD

**Issue by dcwbq** [spidernet-io/egressgateway#345]
{"level":"ERROR","ts":"2023-05-18T09:59:17.458Z","caller":"controller/controller.go:211","msg":"Could not wait for Cache to sync%!(EXTRA []interface {}=[])","error":"failed to wait for egressClusterInfo caches to sync: timed out waiting for cache to be synced"}
{"level":"INFO","ts":"2023-05-18T09:59:17.458Z","caller":"manager/internal.go:581","msg":"Stopping and waiting for non leader election runnables","level":0}
{"level":"INFO","ts":"2023-05-18T09:59:17.458Z","caller":"manager/internal.go:585","msg":"Stopping and waiting for leader election runnables","level":0}
{"level":"INFO","ts":"2023-05-18T09:59:17.459Z","caller":"controller/controller.go:248","msg":"Shutdown signal received, waiting for all workers to finish","level":0}
{"level":"INFO","ts":"2023-05-18T09:59:17.459Z","caller":"controller/controller.go:248","msg":"Shutdown signal received, waiting for all workers to finish","level":0}
{"level":"INFO","ts":"2023-05-18T09:59:17.459Z","caller":"controller/controller.go:250","msg":"All workers finished","level":0}
{"level":"INFO","ts":"2023-05-18T09:59:17.459Z","caller":"controller/controller.go:250","msg":"All workers finished","level":0}
{"level":"INFO","ts":"2023-05-18T09:59:17.459Z","caller":"manager/internal.go:591","msg":"Stopping and waiting for caches","level":0}
{"level":"INFO","ts":"2023-05-18T09:59:17.460Z","caller":"manager/internal.go:595","msg":"Stopping and waiting for webhooks","level":0}

**{"level":"INFO","ts":"2023-05-18T09:59:17.460Z","caller":"manager/internal.go:599","msg":"Wait completed, proceeding to shutdown the manager","level":0}
failed to wait for egressClusterInfo caches to sync: timed out waiting for cache to be synced**

**Comment by dcwbq** [comment]
该问题的根因为 cm->egressgateway.egressIgnoreCIDR.podCIDR  默认值为 "calico"，如果集群未安装 calico，则会引发该问题。

建议默认值为 k8s，再自动识别需要 watch  什么资源

@bzsuni

**Comment by weizhoublue** [comment]
需要 考虑 先装 egress ， 后装 calico 的 安装顺序

controller 可 等到 calico crd ready 再 继续工作

**Comment by lou-lan** [comment]
bz 已经修复
