### ISSUE TITLE
Night CI 2023-06-13: Failed (data race)

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#450]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/5259853729

**Comment by bzsuni** [comment]
WARNING: DATA RACE
Read at 0x00c00008dda8 by goroutine 215:
  github.com/spidernet-io/egressgateway/pkg/agent/vxlan.(*Device).add()
      /src/pkg/agent/vxlan/vxlan.go:197 +0xa8
  github.com/spidernet-io/egressgateway/pkg/agent/vxlan.(*Device).Add()
      /src/pkg/agent/vxlan/vxlan.go:174 +0x14d
  github.com/spidernet-io/egressgateway/pkg/agent.(*vxlanReconciler).ensureRoute()
      /src/pkg/agent/vxlan.go:420 +0x795
  github.com/spidernet-io/egressgateway/pkg/agent.(*vxlanReconciler).reconcileEgressNode()
      /src/pkg/agent/vxlan.go:135 +0xfbd
  github.com/spidernet-io/egressgateway/pkg/agent.(*vxlanReconciler).Reconcile()
      /src/pkg/agent/vxlan.go:64 +0x534
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122 +0x16d
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323 +0x4ab
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274 +0x324
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235 +0xc8

Previous write at 0x00c00008dda8 by goroutine 73:
  github.com/spidernet-io/egressgateway/pkg/agent/vxlan.(*Device).setLink()
      /src/pkg/agent/vxlan/vxlan.go:312 +0x9c
  github.com/spidernet-io/egressgateway/pkg/agent/vxlan.(*Device).EnsureLink()
      /src/pkg/agent/vxlan/vxlan.go:80 +0x424
  github.com/spidernet-io/egressgateway/pkg/agent.(*vxlanReconciler).keepVXLAN()
      /src/pkg/agent/vxlan.go:341 +0xfbd
  github.com/spidernet-io/egressgateway/pkg/agent.newEgressNodeController.func1()
      /src/pkg/agent/vxlan.go:464 +0x39

Goroutine 215 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:231 +0x806
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:242 +0x2c8
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go:219 +0x1c1
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func2()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go:222 +0x47

Goroutine 73 (running) created at:
  github.com/spidernet-io/egressgateway/pkg/agent.newEgressNodeController()
      /src/pkg/agent/vxlan.go:464 +0x9c5
  github.com/spidernet-io/egressgateway/pkg/agent.New()
      /src/pkg/agent/agent.go:62 +0x64a
  github.com/spidernet-io/egressgateway/cmd/agent/cmd.run()
      /src/cmd/agent/cmd/root.go:61 +0x64
  github.com/spidernet-io/egressgateway/cmd/agent/cmd.glob..func1()
      /src/cmd/agent/cmd/root.go:50 +0x2ac
  github.com/spf13/cobra.(*Command).execute()
      /src/vendor/github.com/spf13/cobra/command.go:944 +0xc41
  github.com/spf13/cobra.(*Command).ExecuteC()
      /src/vendor/github.com/spf13/cobra/command.go:1068 +0x5fa
  github.com/spf13/cobra.(*Command).Execute()
      /src/vendor/github.com/spf13/cobra/command.go:992 +0x3c
  github.com/spidernet-io/egressgateway/cmd/agent/cmd.Execute()
      /src/cmd/agent/cmd/root.go:86 +0x25
  main.main()
      /src/cmd/agent/main.go:11 +0x24

**Comment by bzsuni** [comment]
WARNING: DATA RACE
Read at 0x00c000724fc0 by goroutine 215:
  github.com/spidernet-io/egressgateway/pkg/agent/vxlan.(*Device).add()
      /src/pkg/agent/vxlan/vxlan.go:197 +0xc4
  github.com/spidernet-io/egressgateway/pkg/agent/vxlan.(*Device).Add()
      /src/pkg/agent/vxlan/vxlan.go:174 +0x14d
  github.com/spidernet-io/egressgateway/pkg/agent.(*vxlanReconciler).ensureRoute()
      /src/pkg/agent/vxlan.go:420 +0x795
  github.com/spidernet-io/egressgateway/pkg/agent.(*vxlanReconciler).reconcileEgressNode()
      /src/pkg/agent/vxlan.go:135 +0xfbd
  github.com/spidernet-io/egressgateway/pkg/agent.(*vxlanReconciler).Reconcile()
      /src/pkg/agent/vxlan.go:64 +0x534
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122 +0x16d
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323 +0x4ab
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274 +0x324
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235 +0xc8

Previous write at 0x00c000724fc0 by goroutine 73:
  github.com/vishvananda/netlink.LinkDeserialize()
      /src/vendor/github.com/vishvananda/netlink/link_linux.go:2034 +0x1a67
  github.com/vishvananda/netlink.execGetLink()
      /src/vendor/github.com/vishvananda/netlink/link_linux.go:1751 +0x144
  github.com/vishvananda/netlink.(*Handle).LinkByName()
      /src/vendor/github.com/vishvananda/netlink/link_linux.go:1671 +0x6d4
  github.com/vishvananda/netlink.LinkByName()
      /src/vendor/github.com/vishvananda/netlink/link_linux.go:1651 +0x124
  github.com/spidernet-io/egressgateway/pkg/agent/vxlan.(*Device).ensureLink()
      /src/pkg/agent/vxlan/vxlan.go:109 +0xcf
  github.com/spidernet-io/egressgateway/pkg/agent/vxlan.(*Device).EnsureLink()
      /src/pkg/agent/vxlan/vxlan.go:76 +0x404
  github.com/spidernet-io/egressgateway/pkg/agent.(*vxlanReconciler).keepVXLAN()
      /src/pkg/agent/vxlan.go:341 +0xfbd
  github.com/spidernet-io/egressgateway/pkg/agent.newEgressNodeController.func1()
      /src/pkg/agent/vxlan.go:464 +0x39

Goroutine 215 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:231 +0x806
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:242 +0x2c8
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go:219 +0x1c1
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func2()
      /src/vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go:222 +0x47

Goroutine 73 (running) created at:
  github.com/spidernet-io/egressgateway/pkg/agent.newEgressNodeController()
      /src/pkg/agent/vxlan.go:464 +0x9c5
  github.com/spidernet-io/egressgateway/pkg/agent.New()
      /src/pkg/agent/agent.go:62 +0x64a
  github.com/spidernet-io/egressgateway/cmd/agent/cmd.run()
      /src/cmd/agent/cmd/root.go:61 +0x64
  github.com/spidernet-io/egressgateway/cmd/agent/cmd.glob..func1()
      /src/cmd/agent/cmd/root.go:50 +0x2ac
  github.com/spf13/cobra.(*Command).execute()
      /src/vendor/github.com/spf13/cobra/command.go:944 +0xc41
  github.com/spf13/cobra.(*Command).ExecuteC()
      /src/vendor/github.com/spf13/cobra/command.go:1068 +0x5fa
  github.com/spf13/cobra.(*Command).Execute()
      /src/vendor/github.com/spf13/cobra/command.go:992 +0x3c
  github.com/spidernet-io/egressgateway/cmd/agent/cmd.Execute()
      /src/cmd/agent/cmd/root.go:86 +0x25
  main.main()
      /src/cmd/agent/main.go:11 +0x24
