### ISSUE TITLE
egressgateway ippools IP repeat

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#538]
**Describe the version**
egress v0.2.0-rc1

**Describe the bug**
when egressgateway ippools ip repeat, it can create

**Hwo To Reproduce**
create egressgateway use same ippools

**Expected behavior**
we expect that when ippools ip repeat its not allowed to create

**Screenshots and log**
![image](https://github.com/spidernet-io/egressgateway/assets/86399306/b91c8891-2261-45f3-bb38-7d16cf06b201)

**Additional context**

**Comment by weizhoublue** [comment]
any update on this ?

**Comment by bzsuni** [comment]
> any update on this ?

There is no PR fix for this issue yet
