### ISSUE TITLE
nightly e2e failed

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#557]
https://github.com/spidernet-io/egressgateway/actions/runs/5479625454/jobs/9987160041

https://github.com/spidernet-io/egressgateway/commit/d1ce4a91ec6cf406e1117ff9d51ef6b534a9605c

remove the target in CI

**Comment by lou-lan** [comment]
Fixed in https://github.com/spidernet-io/egressgateway/pull/547. 
We don't need swagger checks, it's not cleaned up the first time
