### ISSUE TITLE
Night CI 2023-07-10: Failed ( tcp reset by peer )

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#570]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/5512445094

**Comment by bzsuni** [comment]
read tcp 172.40.56.1:49380->172.18.0.5:63380: read: connection reset by peer

**Comment by bzsuni** [comment]
During the process of eip taking effect, tcp "connection reset by peer" is caused due to source ip change
