### ISSUE TITLE
Night CI 2023-07-19: Failed (failed check egci status after create calico ippool)

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#605]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/5603541553

**Comment by bzsuni** [comment]
[It] create or update calico ippool [I00002]
  /home/runner/work/egressgateway/egressgateway/test/e2e/egressclusterinfo/egressclusterinfo_test.go:55

  Timeline >>
  > Enter [BeforeEach] Egressclusterinfo - /home/runner/work/egressgateway/egressgateway/test/e2e/egressclusterinfo/egressclusterinfo_test.go:25 @ 07/19/23 20:12:48.054
  < Exit [BeforeEach] Egressclusterinfo - /home/runner/work/egressgateway/egressgateway/test/e2e/egressclusterinfo/egressclusterinfo_test.go:25 @ 07/19/23 20:12:48.054 (0s)
  > Enter [It] create or update calico ippool - /home/runner/work/egressgateway/egressgateway/test/e2e/egressclusterinfo/egressclusterinfo_test.go:55 @ 07/19/23 20:12:48.054
  get EgressClusterInfo default
  create calico ippool
  wait calico ippool test-v4-7709 created
  WaitEgressClusterInfoPodCidrUpdated after calicoIPPool created
  check EgressIgnoreCIDR Fields
  eciNodesIPv4: [172.18.0.4 172.18.0.2 172.18.0.3], nodesIPv4: [172.18.0.4 172.18.0.2 172.18.0.3]
  eciNodesIPv6: [], nodesIPv6: []
  eciClusterIPv4: [], serviceIpv4s: [172.41.0.0/16]
  [FAILED] Expected
      <bool>: false
  to be true
  In [It] at: /home/runner/work/egressgateway/egressgateway/test/e2e/egressclusterinfo/egressclusterinfo_test.go:116 @ 07/19/23 20:12:48.243

**Comment by bzsuni** [comment]
fixed in https://github.com/spidernet-io/egressgateway/pull/630
