### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#645]
文档对小白不友好

1. 任何步骤，配置命令要 小白可实施，不能只是一个思路或者 只提部分命令，命令是要符合最佳实践

2. 任何步骤，配置命令后，都要有状态查看的步骤，确认 配置成功

3. 一些 字段说明上，太粗糙，很多重要的注意事项没提及

4. 一些步骤的意义没提及，上来就是输入各种命令

5.

**Comment by lou-lan** [comment]
https://github.com/spidernet-io/egressgateway/pull/724
