### ISSUE TITLE
lock type

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#680]
it suggests to use pkg/lock  instead of standard lock for dead lock dection

(1)
https://github.com/spidernet-io/egressgateway/blob/main/pkg/agent/vxlan/vxlan.go#L22

(2)
https://github.com/spidernet-io/egressgateway/blob/main/pkg/iptables/lock.go#L62

**Comment by lou-lan** [comment]
https://github.com/spidernet-io/egressgateway/pull/681/files
