### ISSUE TITLE
[e2e case] 添加分配 IP 的 case

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#709]
1. 创建 egressgateway，给定 IP 池
2. 不断创建，删除 和 IP 池 IP 数量 相同数量的 policy 使用以上 gateway
3. 创建，删除几轮后，期望 IP 分配 不出错

**Comment by bzsuni** [comment]
> 1. 创建 egressgateway，给定 IP 池
> 2. 不断创建，删除 和 IP 池 IP 数量 相同数量的 policy 使用以上 gateway
> 3. 创建，删除几轮后，期望 IP 分配 不出错

这个用例这样设计有点问题，因为不同的 policy 有可能使用相同的 IP 作为出口 IP，
所以有关 IP 分配的用例，我们可以如何设计？@lou-lan @dcwbq

**Comment by dcwbq** [comment]
1、创建一个 IP池中有100 个 IP 的 EgressGateway ，该egw 选择三个节点可作为出口节点
2、创建 120 个 useNodeIP=false 的 egp，创建 10 个 useNodeIP=true 的 egp，都引用上述 egw
3、检查 egw.status 中的值，如果出现一个 egp 同时在多个 节点生效，或者出现一个 EIP 在多个节点上生效，则表示有bug
4、上述两种 egp  各留 2 个，删除其余的 egp
5、检查 egw.status 中的值，除了未删除的egp及其引用的 EIP，其余 EIP 及 egp 的信息都被删除

**Comment by weizhoublue** [comment]
> 为不同的 policy 有可能使用相同的 IP 作为出口 IP



> > 1. 创建 egressgateway，给定 IP 池
> > 2. 不断创建，删除 和 IP 池 IP 数量 相同数量的 policy 使用以上 gateway
> > 3. 创建，删除几轮后，期望 IP 分配 不出错
> 
> 这个用例这样设计有点问题，因为不同的 policy 有可能使用相同的 IP 作为出口 IP， 所以有关 IP 分配的用例，我们可以如何设计？@lou-lan @dcwbq @weizhoublue

用例就是为了 创建 独占IP 的 policy 来测试

**Comment by bzsuni** [comment]
我们没有办法自动创建独占 IP 的 policy，除非每个policy 都手动指定？
@lou-lan @dcwbq @weizhoublue

**Comment by bzsuni** [comment]
1、创建 gateway 有 100 个 IP 的池
2、创建 100 个 policy，不断启杀几轮
3、最后存在 100 个 policy 时，检查 egw 的 status，期望所有 policy ip 无重复
4、最后 删除 100 个 policy 后，检查  IP 都被释放
@lou-lan @dcwbq @weizhoublue

**Comment by bzsuni** [comment]
用例设计修改：

1. 创建池有100 个 IP 的 egw
2. rr 模式创建 120 个 egp
3. 启杀启 120 egp， 
  期望：
  （1）100 policy 可以正常分到 IP，20 个 policy 不能分配到 IP
  （2）100 个 IP 无复用情况
  （3）egw status 和 egp 状态一致
  （4）连通性正常，pod 出口 IP 应该为其使用 policy 的 eip
4. 杀 120-egp，
  期望：
  （1）egw status 为空，可用 IP 为 100
  （2）连通性，pod 出口 IP 不为 eip

@lou-lan @weizhoublue @dcwbq
