### ISSUE TITLE
Night CI 2023-08-30: Failed when obtain the EgressGateway 

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#732]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/6029479462

**Comment by bzsuni** [comment]
• [0.498 seconds]
Test default egress gateway [DefaultEgressGateway, G00017]
/home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:14
  test cluster default egress gateway
  /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:71

  Timeline >>
  > Enter [BeforeAll] Test default egress gateway - /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:20 @ 08/30/23 20:28:51.038
  < Exit [BeforeAll] Test default egress gateway - /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:20 @ 08/30/23 20:28:51.038 (0s)
  > Enter [It] test cluster default egress gateway - /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:71 @ 08/30/23 20:28:51.038
  < Exit [It] test cluster default egress gateway - /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:71 @ 08/30/23 20:28:51.536 (498ms)
  << Timeline
------------------------------
• [FAILED] [0.169 seconds]
Test default egress gateway [DefaultEgressGateway, G00017]
/home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:14
  [It] test namespace default egress gateway
  /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:87

  Timeline >>
  > Enter [It] test namespace default egress gateway - /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:87 @ 08/30/23 20:28:51.537
  [FAILED] Unexpected error:
      <*errors.StatusError | 0xc0003f0a00>: 
      admission webhook "egressgateway.egressgateway.spidernet.io" denied the request: when egp(test-default-egw-policy2) UseNodeIP is false, failed to obtain the EgressGateway: egressgateways.egressgateway.spidernet.io "ns-default" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "admission webhook \"egressgateway.egressgateway.spidernet.io\" denied the request: when egp(test-default-egw-policy2) UseNodeIP is false, failed to obtain the EgressGateway: egressgateways.egressgateway.spidernet.io \"ns-default\" not found",
              Reason: "Forbidden",
              Details: nil,
              Code: 403,
          },
      }
  occurred
  In [It] at: /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:101 @ 08/30/23 20:28:51.628
  < Exit [It] test namespace default egress gateway - /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:87 @ 08/30/23 20:28:51.628 (90ms)
  > Enter [AfterAll] Test default egress gateway - /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:110 @ 08/30/23 20:28:51.628
  < Exit [AfterAll] Test default egress gateway - /home/runner/work/egressgateway/egressgateway/test/e2e/egressgateway/default_egressgateway_test.go:110 @ 08/30/23 20:28:51.706 (78ms)
  << Timeline

**Comment by bzsuni** [comment]
![image](https://github.com/spidernet-io/egressgateway/assets/86399306/6a02b2e2-e363-496f-80d7-91f8e1548e01)

**Comment by lou-lan** [comment]
Fixed
