### ISSUE TITLE
Night CI 2023-09-05: Failed -- check eip failed 

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#753]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/6081110698

**Comment by bzsuni** [comment]
STEP: case P00008: create policy with empty `EgressIP` - /home/runner/work/egressgateway/egressgateway/test/e2e/egresspolicy/egresspolicy_test.go:107 @ 09/05/23 06:51:12.64
  Create egressPolicy: policy-lluo-162
  GenerateEgressPolicyYaml: policy-lluo-162
  WaitEgressPolicyEipUpdated...
  v4Eip: 172.18.1.5, v6Eip: , allocatorPolicy: default, useNodeIP: false
  Check export ip in dsA: dsa-jo1d-539 pods
  checking in 0th pod: dsa-jo1d-539-s5hdp
  checking in 1th pod: dsa-jo1d-539-tvgmk
  checking in 2th pod: dsa-jo1d-539-vxqxk
  [FAILED] Unexpected error:
      <*errors.errorString | 0xc00005f480>: 
      time out
      {s: "time out"}
  occurred
  In [It] at: /home/runner/work/egressgateway/egressgateway/test/e2e/egresspolicy/egresspolicy_test.go:238 @ 09/05/23 06:52:06.214

**Comment by lou-lan** [comment]
我们更新了这一部分的 e2e 逻辑
