### ISSUE TITLE
Night CI 2023-09-09: Failed -- failed to update egci

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#773]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/6132885682

**Comment by bzsuni** [comment]
getEgressClusterInfoPodCidr
  podV4Cidr: [172.40.0.0/16], eciPodCidrV4: [172.40.0.0/16 172.40.0.0/16]
  podV6Cidr: [fd40::/48 fddd:1f4a:7eb6::0/112], eciPodCidrV6: [fd40::/48 fd40::/48 fddd:1f4a:7eb6::0/112]
  getEgressClusterInfoPodCidr
  podV4Cidr: [172.40.0.0/16], eciPodCidrV4: [172.40.0.0/16 172.40.0.0/16]
  podV6Cidr: [fd40::/48 fddd:1f4a:7eb6::0/112], eciPodCidrV6: [fd40::/48 fddd:1f4a:7eb6::0/112 fd40::/48]
  getEgressClusterInfoPodCidr
  podV4Cidr: [172.40.0.0/16], eciPodCidrV4: [172.40.0.0/16 172.40.0.0/16]
  podV6Cidr: [fd40::/48 fddd:1f4a:7eb6::0/112], eciPodCidrV6: [fd40::/48 fd40::/48 fddd:1f4a:7eb6::0/112]
  getEgressClusterInfoPodCidr
  podV4Cidr: [172.40.0.0/16], eciPodCidrV4: [172.40.0.0/16 172.40.0.0/16]
  podV6Cidr: [fd40::/48 fddd:1f4a:7eb6::0/112], eciPodCidrV6: [fd40::/48 fd40::/48 fddd:1f4a:7eb6::0/112]
  getEgressClusterInfoPodCidr
  podV4Cidr: [172.40.0.0/16], eciPodCidrV4: [172.40.0.0/16 172.40.0.0/16]
  podV6Cidr: [fd40::/48 fddd:1f4a:7eb6::0/112], eciPodCidrV6: [fd40::/48 fddd:1f4a:7eb6::0/112 fd40::/48]
  getEgressClusterInfoPodCidr
  podV4Cidr: [172.40.0.0/16], eciPodCidrV4: [172.40.0.0/16 172.40.0.0/16]
  podV6Cidr: [fd40::/48 fddd:1f4a:7eb6::0/112], eciPodCidrV6: [fd40::/48 fd40::/48 fddd:1f4a:7eb6::0/112]
  [FAILED] Unexpected error:
      <*errors.errorString | 0xc0003a6460>: 
      time out
      {s: "time out"}
  occurred
  In [It] at: /home/runner/work/egressgateway/egressgateway/test/e2e/egressclusterinfo/egressclusterinfo_test.go:122 @ 09/09/23 20:13:27.44
  < Exit [It] Create or update calico ippool -

**Comment by bzsuni** [comment]
fixed by #782
