### ISSUE TITLE
Night CI 2023-09-13: Failed -- long lock

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#790]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/6177236842

**Comment by bzsuni** [comment]
{"level":"error","ts":"2023-09-13T20:10:05.476Z","caller":"controller/egress_policy.go:97","msg":"update egresspolicy status","name":"ns-default","kind":"EgressGateway","status":{"eip":{}},"error":"Operation cannot be fulfilled on egresspolicies.egressgateway.spidernet.io \"test-default-egw-policy2\": StorageError: invalid object, Code: 4, Key: /registry/egressgateway.spidernet.io/egresspolicies/default/test-default-egw-policy2, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 9ff69ade-e212-4991-ae1b-04831b36cb24, UID in object meta: ","stacktrace":"github.com/spidernet-io/egressgateway/pkg/controller.(*egpReconciler).reconcileEGW\n\t/src/pkg/controller/egress_policy.go:97\ngithub.com/spidernet-io/egressgateway/pkg/controller.(*egpReconciler).Reconcile\n\t/src/pkg/controller/egress_policy.go:41\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226"}
{"level":"error","ts":"2023-09-13T20:10:05.483Z","caller":"controller/controller.go:324","msg":"Reconciler error","controller":"egresspolicy","object":{"name":"ns-default","namespace":"EgressGateway/"},"namespace":"EgressGateway/","name":"ns-default","reconcileID":"d35b83d4-521f-44fb-8db3-61b83674da99","error":"Operation cannot be fulfilled on egresspolicies.egressgateway.spidernet.io \"test-default-egw-policy2\": StorageError: invalid object, Code: 4, Key: /registry/egressgateway.spidernet.io/egresspolicies/default/test-default-egw-policy2, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 9ff69ade-e212-4991-ae1b-04831b36cb24, UID in object meta: ","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226"}

**Comment by bzsuni** [comment]
same with #781
