### ISSUE TITLE
gateway eip 在多个节点上生效

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#806]
描述：
egressgateway yaml 中，观察到 相同的 eip 在不同的节点上生效

**Comment by bzsuni** [comment]
egressgateway yaml：

[root@master-32 yamls]# k get egw test-gateway -oyaml
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"egressgateway.spidernet.io/v1beta1","kind":"EgressGateway","metadata":{"annotations":{},"name":"test-gateway"},"spec":{"ippools":{"i                                                                                pv4":["10.6.1.2-10.6.1.12"],"ipv4DefaultEIP":"10.6.1.2","ipv6":["fddd:10::2-fddd:10::c"]},"nodeSelector":{"selector":{"matchLabels":{"isgateway":"y"}}}}}
  creationTimestamp: "2023-09-18T10:53:06Z"
  generation: 1
  name: test-gateway
  resourceVersion: "5453316"
  uid: 4324606e-c56f-41ce-a4a6-997026ebcb87
spec:
  ippools:
    ipv4:
    - 10.6.1.2-10.6.1.12
    ipv4DefaultEIP: 10.6.1.2
    ipv6:
    - fddd:10::2-fddd:10::c
  nodeSelector:
    selector:
      matchLabels:
        isgateway: "y"
status:
  nodeList:
  - epis:
    - ipv4: 10.6.1.2
      policies:
      - name: test-policy-001
        namespace: default
    name: master-32
    status: Ready
  - epis:
    - ipv4: 10.6.1.2
      policies:
      - name: test-cluster-policy-001
      - name: test-cluster-policy-002
    name: worker-33
  - epis:
    - ipv4: 10.6.1.2
      policies:
      - name: test-policy-002
        namespace: test
    name: worker-34
    status: Ready

**Comment by weizhoublue** [comment]
look like a big issue, must fix

**Comment by lou-lan** [comment]
这个是 controller 更新 egressgateway 的 status 问题
