### ISSUE TITLE
[ egressgateway-controller ] controller 报 panic

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#831]
创建 egw 使用 空池，
当创建命名空间级别 policy ，设置 Spec.EgressIP.UseNodeIP = true
egressgateway-controller 会报 controller

1. 创建 egw
```
apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  creationTimestamp: "2023-10-11T03:24:38Z"
  generation: 1
  name: egw-sit
  resourceVersion: "96632"
  uid: 1953781c-185c-48a8-8105-7166dd560ca9
spec:
  ippools: {}
  nodeSelector:
    selector:
      matchLabels:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: egressgateway-control-plane
        kubernetes.io/os: linux
        node-role.kubernetes.io/control-plane: ""
        node.kubernetes.io/exclude-from-external-load-balancers: ""
status:
  nodeList:
  - name: egressgateway-control-plane
    status: Ready

```
2. 创建 policy
```
  metadata:
    creationTimestamp: null
    name: egp-voluptatem
    namespace: default
  spec:
    appliedTo: {}
    destSubnet:
    - 10.10.0.0/18
    egressGatewayName: egw-sit
    egressIP: {}
  status:
    eip: {}

```
3. controller 日志报错
2023/10/11 03:24:38 http: panic serving 172.40.228.128:61130: runtime error: invalid memory address or nil pointer dereference
goroutine 7452 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1854 +0x245
panic({0x338cc00, 0x4779ec0})
        /usr/local/go/src/runtime/panic.go:890 +0x262
github.com/spidernet-io/egressgateway/pkg/controller/webhook.ValidateHook.func1({_, _}, {{{0xc0001d8840, 0x24}, {{0xc00004dde0, 0x1a}, {0xc0007315e9, 0x7}, {0xc0007315f4, 0xc}}, ...}})
        /src/pkg/controller/webhook/validate.go:133 +0x944
sigs.k8s.io/controller-runtime/pkg/webhook/admission.HandlerFunc.Handle(_, {_, _}, {{{0xc0001d8840, 0x24}, {{0xc00004dde0, 0x1a}, {0xc0007315e9, 0x7}, {0xc0007315f4, ...}}, ...}})
        /src/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:113 +0x115
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc0001d8840, 0x24}, {{0xc00004dde0, 0x1a}, {0xc0007315e9, 0x7}, {0xc0007315f4, ...}}, ...}})
        /src/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:169 +0x395
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc000594c80, {0x7fbe49b2b178, 0xc0003b1a90}, 0xc000c4e600)
        /src/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:98 +0x1658
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7fbe49b2b178, 0xc0003b1a90}, 0xc000c4e600)
        /src/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:60 +0x1ef
net/http.HandlerFunc.ServeHTTP(0xc00014e0f0, {0x7fbe49b2b178, 0xc0003b1a90}, 0xc000c4e600)
        /usr/local/go/src/net/http/server.go:2122 +0x6f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x3b6bb70, 0xc00064e700}, 0xc000c4e600)
        /src/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:147 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00014e300, {0x3b6bb70, 0xc00064e700}, 0xc000c4e600)
        /usr/local/go/src/net/http/server.go:2122 +0x6f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x3b6bb70, 0xc00064e700}, 0xc000c4e600)
        /src/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:109 +0x133
net/http.HandlerFunc.ServeHTTP(0xc0005980c0, {0x3b6bb70, 0xc00064e700}, 0xc000c4e600)
        /usr/local/go/src/net/http/server.go:2122 +0x6f
net/http.(*ServeMux).ServeHTTP(0xc0001e3d80, {0x3b6bb70, 0xc00064e700}, 0xc000c4e600)
        /usr/local/go/src/net/http/server.go:2500 +0x2da
net/http.serverHandler.ServeHTTP({0xc0005ce0f0}, {0x3b6bb70, 0xc00064e700}, 0xc000c4e600)
        /usr/local/go/src/net/http/server.go:2936 +0x882
net/http.(*conn).serve(0xc000125b90, {0x3b6c8f0, 0xc00036e910})
        /usr/local/go/src/net/http/server.go:1995 +0x2c5e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0x1074

**Comment by lou-lan** [comment]
https://github.com/spidernet-io/egressgateway/commit/930c591508cb96a6e9269957d77f96ff6e56457f
