### ISSUE TITLE
[ feature ] egw 需要有 IP 使用情况展示

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#838]
egw yaml 中 应该有 IP 池 IP 总数及已用数量 展示

在 kubectl get -o wide 时，最后也能展示出 ip 用量信息，方便 运维

**Comment by lou-lan** [comment]
可以考虑使用 kubectl plugin 来实现，如果 status 引入一个计数，需要在所有分配 IP 的函数增加使用量计算。另外社区有零星的试用者，在 CRD version 不升级的情况下，会有不兼容的情况，已经安装的需要卸载重新安装。
