### ISSUE TITLE
[ clusterPolicy 创建 ] 当 egw 空池，egcp 设置 Spec.EgressIP.UseNodeIP = false 时，创建 egcp 成功

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#844]
## 相关用例：G00019，pr：#849 
期待 不能 egcp 应该不可以被创建

**Comment by weizhoublue** [comment]
不能创建一种实现，

其实，也可以 创建，只是 egcp 的 状态是 pending 之类的， 不能工作

**Comment by bzsuni** [comment]
好的

**Comment by lou-lan** [comment]
这个期待是能创建的

**Comment by bzsuni** [comment]
> 这个期待是能创建的 @bzsuni

@dcwbq 的用例文档，写的是不能创建。
这个后续可以大家同步一下 @lou-lan

**Comment by lou-lan** [comment]
> > 这个期待是能创建的 @bzsuni
> 
> @dcwbq 的用例文档，写的是不能创建。 这个后续可以大家同步一下 @lou-lan

不能创建，我看错了
