### ISSUE TITLE
Reduce unnecessary EIP chnage

### ISSUE THREAD

**Issue by lou-lan** [spidernet-io/egressgateway#852]
### EN

Here are three nodes, `A`, `B`, and `C`. The Egress IP assigned to Node `B`.  
* Shutdown Node `B`.
* Egress IP from `B` transfer to Node `C`.
* Start Node B, EIP back to Node B.

We expect: EIP stay at Node `C`.

### ZH

这里有三个节点，`A`、`B` 和 `C`。Egress IP 被分配给节点 `B`。

现象：

* 关闭节点 `B`。
* `B` 节点的 Egress IP 转移到节点 `C`。
* 启动节点 `B`，EIP 转移到节点 `B`。

期望：EIP 保留在节点 `C` 上。

**Comment by dcwbq** [comment]
这个问题应该修复，后面验证一下没问题后可以关闭
