### ISSUE TITLE
[ optimize ] 删除 egressgateway 使用 finalizer 机制

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#866]

**Comment by dcwbq** [comment]
觉得没有必要，用户功能感知不强，代码逻辑却要复杂不少
spiderpool ippool 做这个功能是因为有自动创建池的功能

**Comment by bzsuni** [comment]
删除 `egressgateway ` 思路：
1. 创建 `egressgateway ` 时，在 `webhook` 加 `finalizer`
2. 删除 `policy ` 时，判断其引用的 `gateway ` 是否是 `deleting ` 状态，并判断是否是最后一个引用这个 `gateway` 的 `policy`
3. 如果是步骤2判断的结果，则将 `egressgateway ` 中的 `finalizer ` 删除
