### ISSUE TITLE
编辑 EgressClusterPolicy 的 `spec.egressIP.IP` 或 `spec.egressGatewayName` 未报错

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#887]
ref #886

### 情况

编辑 `spec.EgressIP.IP` 和 `spec.egressGatewayName` 这两个字段没有报错。

### 期望 
编辑 `spec.EgressIP.IP` 和 `spec.egressGatewayName` 这两个字段，会被拒绝。

**Comment by lou-lan** [comment]
Fixed in https://github.com/spidernet-io/egressgateway/pull/911/files
