### ISSUE TITLE
[ e2e 用例 ] 增删 pod 后，判断 pod 出口 IP 是否符合预期

### ISSUE THREAD

**Issue by bzsuni** [spidernet-io/egressgateway#927]
### 用例目的
校验 `EgressPolicy` 或 `EgressClusterPolicy` 匹配的 Pod（应用） 在 **扩容/缩容** 后是否正常工作。

### 用例思路

不断增删 policy 所匹配到的 pods，几轮增删后，判断所有 pod 的出口 IP

#### 用例步骤

1. 创建 `EgressGateway`
2. 创建 `EgressPolicy` 
3. 50 个 Pod 增删增操作
4. 等全部 Running 后，期望 `EgressEndpointSlice` 状态 与 `EgressPolicy` 所选 `Pod` 一致，期望 `Pod` 出口 IP 为 eip
5. 删除所有 Pod 后，期望 `EgressEndpointSlice` 被删除

@lou-lan @weizhoublue @dcwbq 
请 review 提出修改或增强建议

**Comment by lou-lan** [comment]
做了一些格式上的调整，Pod 扩容和缩容的副本数，要在 github action 能承载的范围内。

**Comment by bzsuni** [comment]
> 做了一些格式上的调整，Pod 扩容和缩容的副本数，要在 github action 能承载的范围内。假设 github action 起 50 个 Pod 资源比较紧张了，那就设置的副本数少一点。

嗯好
