### ISSUE TITLE
文档站中英文安装文档排版错误

### ISSUE THREAD

**Issue by dcwbq** [spidernet-io/egressgateway#952]
<img width="393" alt="企业微信截图_3426756a-19bc-47d9-9e8e-03a11bbc41d5" src="https://github.com/spidernet-io/egressgateway/assets/62228454/fc9d825c-9155-4a69-87ef-6230f5dd0bd4">
<img width="366" alt="企业微信截图_70a76c87-bcde-4a1c-8a49-7b68d80f956b" src="https://github.com/spidernet-io/egressgateway/assets/62228454/798d09cb-7ee4-4a51-809a-a1cce3850dec">

**Comment by lou-lan** [comment]
![截屏2023-11-09 16 37 53](https://github.com/spidernet-io/egressgateway/assets/13095837/0ea21141-fe9e-4b67-b370-63549ceea291)

Fixed. link https://spidernet-io.github.io/egressgateway/dev/usage/Install/
