### ISSUE TITLE
install--No policy status and not found EndpointSlices name

### ISSUE THREAD

**Issue by Stella0621** [spidernet-io/egressgateway#956]
1.set chainInsertMode--命令行错误，已修改
2.为应用创建 EgressPolicy CR 对象失败--已更改ymal

<img width="1434" alt="image" src="https://github.com/spidernet-io/egressgateway/assets/97972450/db4d2d0c-fd56-4803-86ad-d846b05ece76">

3.查看 EgressEndpointSlices 的状态---not found "name: test-kvlp6"
4.测试--这步示例$ kubectl exec -it visitor-6764bb48cc-29vq9 bash，not found“visitor-6764bb48cc-29vq9 ”

**Comment by lou-lan** [comment]
@bzsuni Should this issue be classified as a bug or a documentation problem?

**Comment by bzsuni** [comment]
ref: #955

**Comment by bzsuni** [comment]
> @bzsuni Should this issue be classified as a bug or a documentation problem?

1 and 2 are documentation problems, while 3 and 4 are not bugs.
